name: Build Mac Only

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: |
        npm install
        npm install -g electron-builder

    - name: Build Vue
      run: npm run build

    - name: Debug file list
      run: ls -la

    - name: Build Electron for Mac
      run: |
        npx electron-builder --mac --dir
        npx electron-builder --mac --dmg
      env:
        CI: true
        DEBUG: electron-builder

    - name: Upload Mac Build
      uses: actions/upload-artifact@v4
      with:
        name: build-mac
        path: build/
